/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report API liveness and per-dependency reachability.
         *
         *     Always ``200`` while the API process is alive — the compose healthcheck
         *     gates on the process, and per-dependency state lives in the body so a
         *     flapping backing service doesn't flap the ``api`` container.
         *
         *     Returns:
         *         The aggregate flag and each service's probe outcome.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description Expose the registered capabilities and valid ranges.
         *
         *     Returns:
         *         Registry contents (retrievers, chunkers, OCR engines, model types)
         *         plus the numeric knobs' valid ranges.
         */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List every conversation, most recently updated first.
         *
         *     Args:
         *         store: The per-request conversation store.
         *
         *     Returns:
         *         Summaries with message counts.
         */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Start a conversation.
         *
         *     Args:
         *         payload: Optional explicit title (the first chat turn auto-titles
         *             otherwise).
         *         store: The per-request conversation store.
         *
         *     Returns:
         *         The created conversation's summary.
         */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Fetch a full transcript: messages plus each answer's stored sources.
         *
         *     Args:
         *         conversation_id: The conversation to fetch.
         *         store: The per-request conversation store.
         *
         *     Returns:
         *         The transcript, oldest message first.
         *
         *     Raises:
         *         HTTPException: ``404 conversation_not_found`` for an unknown id.
         */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a conversation; messages and sources cascade.
         *
         *     Args:
         *         conversation_id: The conversation to delete.
         *         store: The per-request conversation store.
         *
         *     Returns:
         *         An empty ``204`` response.
         *
         *     Raises:
         *         HTTPException: ``404 conversation_not_found`` for an unknown id.
         */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Answer one question as a typed SSE stream (spec_v2 §4.3).
         *
         *     Event order: ``retrieval`` (the provenance payload) → ``reasoning``/
         *     ``token`` deltas → ``done`` (ids, full answer, usage + per-stage
         *     latency). A failure after the stream opened emits an in-band ``error``
         *     event instead. Aborted turns (client disconnect) persist nothing — the
         *     turn is persisted *at* ``done``.
         *
         *     Args:
         *         plan: The validated request plan.
         *
         *     Yields:
         *         The framed SSE events, in protocol order.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Expose the metric catalog for a Prometheus scrape.
         *
         *     Returns:
         *         The default registry rendered in the Prometheus text format
         *         (``text/plain; version=0.0.4``).
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatOverrides
         * @description Per-request overrides of query-time settings (spec_v2 §4.2).
         *
         *     Phase 2 honors the two knobs the thin client needs; the persisted
         *     runtime-override layer (spec_v2 §4.7) lands with its GUI in Phase 8.
         *     Unknown fields are rejected so a typo'd override fails loudly instead
         *     of silently running with defaults.
         *
         *     Attributes:
         *         retrieval_method: Registry name of the retrieval method for this
         *             question only (``semantic`` | ``bm25`` | ``hybrid`` |
         *             ``reranked``).
         *         top_k: Number of chunks retrieved for this question only.
         */
        ChatOverrides: {
            /** Retrieval Method */
            retrieval_method?: string | null;
            /** Top K */
            top_k?: number | null;
        };
        /**
         * ChatRequest
         * @description Body of ``POST /api/chat`` (spec_v2 §4.2).
         *
         *     Attributes:
         *         query: The user's question.
         *         conversation_id: Existing conversation to append the turn to; a new
         *             conversation is created when omitted.
         *         overrides: Optional per-request setting overrides.
         */
        ChatRequest: {
            /** Query */
            query: string;
            /** Conversation Id */
            conversation_id?: string | null;
            overrides?: components["schemas"]["ChatOverrides"] | null;
        };
        /**
         * ConfigResponse
         * @description Response of ``GET /api/config`` — static capabilities (spec_v2 §4.2).
         *
         *     The GUI builds its settings controls from this, so a newly registered
         *     implementation (one file + one import) appears in the UI automatically.
         *
         *     Attributes:
         *         retrievers: Registered retrieval method names.
         *         chunkers: Registered chunking strategy names.
         *         ocr_engines: Available OCR engine names.
         *         model_types: Valid ``get_model`` types.
         *         ranges: Valid ranges for the numeric query-time knobs, keyed by
         *             setting name (lowercase).
         */
        ConfigResponse: {
            /** Retrievers */
            retrievers: string[];
            /** Chunkers */
            chunkers: string[];
            /** Ocr Engines */
            ocr_engines: string[];
            /** Model Types */
            model_types: string[];
            /** Ranges */
            ranges: {
                [key: string]: components["schemas"]["NumericRange"];
            };
        };
        /**
         * ConversationCreateRequest
         * @description Body of ``POST /api/conversations``.
         *
         *     Attributes:
         *         title: Optional explicit title; defaults to the placeholder the
         *             first chat turn auto-replaces.
         */
        ConversationCreateRequest: {
            /** Title */
            title?: string | null;
        };
        /**
         * ConversationDetailOut
         * @description Response of ``GET /api/conversations/{id}`` — the full transcript.
         *
         *     Attributes:
         *         conversation_id: The app-generated id.
         *         title: Current title.
         *         created_at: Creation timestamp.
         *         updated_at: Last-turn timestamp.
         *         messages: All messages, oldest first, each with its sources.
         */
        ConversationDetailOut: {
            /** Conversation Id */
            conversation_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /**
         * ConversationSummaryOut
         * @description One conversation in the ``GET /api/conversations`` list.
         *
         *     Attributes:
         *         conversation_id: The app-generated id.
         *         title: Current title.
         *         created_at: Creation timestamp.
         *         updated_at: Last-turn timestamp (list ordering key).
         *         message_count: Number of persisted messages.
         */
        ConversationSummaryOut: {
            /** Conversation Id */
            conversation_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * ErrorBody
         * @description The machine-readable error inside the envelope (spec_v2 §4.1).
         *
         *     Attributes:
         *         code: Stable, machine-readable code (e.g. ``"es_unreachable"``) the
         *             GUI maps to an actionable banner.
         *         message: Human-readable detail.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description The structured error envelope every non-2xx response carries.
         *
         *     Attributes:
         *         error: The error body.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response of ``GET /api/health``.
         *
         *     The endpoint answers ``200`` whenever the API process itself is alive —
         *     per-dependency state lives in the body, so a flapping backing service
         *     doesn't mark the ``api`` container unhealthy.
         *
         *     Attributes:
         *         ok: ``True`` when every dependency probe succeeded.
         *         services: Probe result per service name (``llamacpp``,
         *             ``infinity``, ``postgres``, ``elasticsearch``, ``prefect``).
         */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceHealth"];
            };
        };
        /**
         * MessageOut
         * @description One persisted message in a transcript.
         *
         *     Attributes:
         *         message_id: The app-generated id.
         *         role: ``"user"`` or ``"assistant"``.
         *         content: The question or the generated answer.
         *         created_at: Persistence timestamp.
         *         retrieval_method: Retrieval method of an assistant turn.
         *         latency_ms: Per-stage timings of an assistant turn.
         *         reasoning: Captured ``<think>`` stream, if any.
         *         sources: The turn's snapshotted evidence, rank order.
         */
        MessageOut: {
            /** Message Id */
            message_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Retrieval Method */
            retrieval_method?: string | null;
            /** Latency Ms */
            latency_ms?: {
                [key: string]: unknown;
            } | null;
            /** Reasoning */
            reasoning?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["MessageSourceOut"][];
        };
        /**
         * MessageSourceOut
         * @description One snapshotted evidence row of a persisted assistant turn.
         *
         *     Attributes:
         *         rank: Final rank in the answer's evidence (1-based).
         *         chunk_id: Soft reference to the producing chunk.
         *         trace: The spec_v2 §9.1 snapshot: score, content, context, source
         *             provenance, and the serialized retrieval trace.
         */
        MessageSourceOut: {
            /** Rank */
            rank: number;
            /** Chunk Id */
            chunk_id: string;
            /** Trace */
            trace: {
                [key: string]: unknown;
            };
        };
        /**
         * NumericRange
         * @description Valid range of one numeric setting, for GUI control generation.
         *
         *     Attributes:
         *         min: Inclusive lower bound (``None`` = unbounded).
         *         max: Inclusive upper bound (``None`` = unbounded).
         */
        NumericRange: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /**
         * ServiceHealth
         * @description Reachability of one backing service (spec_v2 §4.2).
         *
         *     Attributes:
         *         ok: Whether the service answered its probe.
         *         detail: Failure detail when it didn't (``None`` when healthy).
         */
        ServiceHealth: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * DeltaEvent
         * @description Payload of the SSE ``reasoning`` and ``token`` events.
         *
         *     Attributes:
         *         delta: The next text fragment, in stream order.
         */
        DeltaEvent: {
            /** Delta */
            delta: string;
        };
        /**
         * DoneEvent
         * @description Payload of the terminal SSE ``done`` event (spec_v2 §4.3).
         *
         *     Attributes:
         *         message_id: Persisted assistant message id.
         *         conversation_id: The conversation the turn was persisted into (the
         *             one just created, when the request named none).
         *         answer: The full, ``<think>``-stripped answer (authoritative — the
         *             streamed deltas are best-effort display).
         *         usage: Token usage and per-stage latency.
         */
        DoneEvent: {
            /** Message Id */
            message_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Answer */
            answer: string;
            usage: components["schemas"]["UsageInfo"];
        };
        /**
         * ErrorEvent
         * @description Payload of the in-band SSE ``error`` event.
         *
         *     Emitted when the pipeline fails after the stream already opened (the
         *     200 headers are gone — status can't change; spec_v2 plan decision #7).
         *
         *     Attributes:
         *         code: Stable, machine-readable code.
         *         message: Human-readable detail.
         */
        ErrorEvent: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * RetrievalEvent
         * @description Payload of the SSE ``retrieval`` event — the provenance panel's data.
         *
         *     Emitted once retrieval (+rerank) completes, **before** any answer token
         *     (spec_v2 §4.3): the browser gets the evidence before the prose.
         *
         *     Attributes:
         *         chunks: The retrieved chunks, best first, each carrying its full
         *             metadata record and (when the method fills it) the
         *             :class:`~varagity.stores.records.RetrievalTrace`.
         *         method: The retrieval method that produced them.
         *         top_k: Chunks requested from the retriever.
         *         reranked_to: ``RERANK_TOP_N`` when the ``reranked`` method narrowed
         *             the list; ``None`` otherwise.
         */
        RetrievalEvent: {
            /** Chunks */
            chunks: components["schemas"]["RetrievedChunk"][];
            /** Method */
            method: string;
            /** Top K */
            top_k: number;
            /**
             * Reranked To
             * @default null
             */
            reranked_to: number | null;
        };
        /**
         * RetrievalTrace
         * @description Why one retrieved chunk ranked where it did (spec_v2 §9.2).
         *
         *     Query-time only — computed per answer by the retrievers, never persisted
         *     on the immutable chunk rows. Ranks are 1-based (display-ready); an arm's
         *     rank/score are ``None`` when that arm's ranked list never surfaced the
         *     chunk. Single-arm retrievers report their arm's score/rank as the fused
         *     values (there is nothing to fuse).
         *
         *     Attributes:
         *         semantic_rank: Rank in the semantic (pgvector) arm.
         *         semantic_score: Cosine similarity in the semantic arm.
         *         bm25_rank: Rank in the BM25 (Elasticsearch) arm.
         *         bm25_score: BM25 relevance in that arm.
         *         fused_score: Weighted reciprocal-rank fusion score (spec §11.4).
         *         fused_rank: Rank after fusion.
         *         rerank_score: Cross-encoder relevance (``None`` when reranking is
         *             off the path).
         *         rerank_delta: Positions moved by reranking, ``pre − post`` (+ moved
         *             up / − moved down; ``None`` when reranking is off the path).
         *         final_rank: The rank actually returned to the caller.
         */
        RetrievalTrace: {
            /**
             * Semantic Rank
             * @default null
             */
            semantic_rank: number | null;
            /**
             * Semantic Score
             * @default null
             */
            semantic_score: number | null;
            /**
             * Bm25 Rank
             * @default null
             */
            bm25_rank: number | null;
            /**
             * Bm25 Score
             * @default null
             */
            bm25_score: number | null;
            /** Fused Score */
            fused_score: number;
            /** Fused Rank */
            fused_rank: number;
            /**
             * Rerank Score
             * @default null
             */
            rerank_score: number | null;
            /**
             * Rerank Delta
             * @default null
             */
            rerank_delta: number | null;
            /** Final Rank */
            final_rank: number;
        };
        /**
         * RetrievedChunk
         * @description A chunk returned by a store search, with its relevance score.
         *
         *     Field set mirrors the spec §11.2 ``SELECT`` list; ``metadata`` holds the
         *     full :class:`ChunkRecord` dump persisted at ingest time.
         *
         *     Attributes:
         *         chunk_id: The chunk's primary key.
         *         doc_id: Parent document id.
         *         original_index: Global chunk index (fusion identity).
         *         content: Original chunk text.
         *         context: LLM situating blurb (``None`` when ingested with
         *             ``CONTEXTUALIZE`` off).
         *         metadata: Full persisted metadata record.
         *         score: Similarity score — cosine similarity ``1 - distance`` for the
         *             vector store (higher is better).
         *         trace: Rank provenance attached by the retrievers (spec_v2 §9.2);
         *             ``None`` on raw store results, so pre-trace callers are
         *             unaffected.
         */
        RetrievedChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Original Index */
            original_index: number;
            /** Content */
            content: string;
            /** Context */
            context: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
            /** @default null */
            trace: components["schemas"]["RetrievalTrace"] | null;
        };
        /**
         * UsageInfo
         * @description Token usage and per-stage latency reported by the ``done`` event.
         *
         *     Attributes:
         *         prompt_tokens: Server-reported prompt tokens (``None`` when the
         *             model server reports no usage).
         *         completion_tokens: Server-reported completion tokens (``None`` when
         *             unreported).
         *         latency_ms: Wall-clock milliseconds per stage: ``retrieval``,
         *             ``generation``, ``total``.
         */
        UsageInfo: {
            /**
             * Prompt Tokens
             * @default null
             */
            prompt_tokens: number | null;
            /**
             * Completion Tokens
             * @default null
             */
            completion_tokens: number | null;
            /** Latency Ms */
            latency_ms: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryOut"][];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
