services:

  infinity-embeddings:
    container_name: infinity-embeddings
    image: michaelf34/infinity:latest-trt-onnx
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${embeddings_volume}:/models
    ports:
      - 192.168.86.21:8081:8081
    environment:
      INFINITY_HOST: '0.0.0.0'
      INFINITY_PORT: 8081
      INFINITY_API_KEY: ${secret_infinity_key}
      INFINITY_ANONYMOUS_USAGE_STATS: '0'
      INFINITY_URL_PREFIX: '/v1'
      INFINITY_MODEL_ID: '/models/multilingual-e5-large-instruct'
      INFINITY_SERVED_MODEL_NAME: 'infloat/multilingual-e5-large-instruct'
      INFINITY_DEVICE: cuda
      INFINITY_DEVICE_ID: '1'
      INFINITY_ENGINE: 'optimum'
    command:
      - v2
    restart: always

  app:
    container_name: varagity
    build: ./
    restart: no
